CREATE DATABASE AIRLINE_DWH;

USE DATABASE AIRLINE_DWH;

CREATE SCHEMA STAGE_1_RAW;

CREATE SCHEMA STAGE_2_INTEGRATION;

CREATE SCHEMA STAGE_3_CORE;

USE SCHEMA STAGE_1_RAW;

#a temporary storage folder inside Snowflake:
CREATE STAGE MY_INTERNAL_STAGE;

CREATE TABLE AUDIT_LOG (
    LOG_ID INT AUTOINCREMENT,
    PROCEDURE_NAME VARCHAR,
    ROWS_AFFECTED INT,
    LOG_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA STAGE_1_RAW;

USE SCHEMA STAGE_1_RAW;

USE SCHEMA AIRLINE_DWH.STAGE_1_RAW;

CREATE OR REPLACE TABLE RAW_AIRLINE_DATA (
    INDEX_COL VARCHAR,
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE VARCHAR,
    NATIONALITY VARCHAR,
    AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    AIRPORT_CONTINENT VARCHAR,
    CONTINENTS VARCHAR,
    DEPARTURE_DATE VARCHAR,
    ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR
);

#stream only processes the new data
CREATE OR REPLACE STREAM AIRLINE_DWH.STAGE_1_RAW.RAW_AIRLINE_STREAM
ON TABLE AIRLINE_DWH.STAGE_1_RAW.RAW_AIRLINE_DATA;

# creating the second schema for stage 2
CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE_2_INTEGRATION.CLEAN_AIRLINE_DATA (
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE INT,
    NATIONALITY VARCHAR,
    AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    AIRPORT_CONTINENT VARCHAR,
    CONTINENTS VARCHAR,
    DEPARTURE_DATE DATE,
    ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR
);