CREATE OR REPLACE PROCEDURE AIRLINE_DWH.STAGE_2_INTEGRATION.LOAD_STAGE_2()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    row_count INTEGER;
BEGIN
    INSERT INTO AIRLINE_DWH.STAGE_2_INTEGRATION.CLEAN_AIRLINE_DATA (
        PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY, 
        AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, 
        CONTINENTS, DEPARTURE_DATE, ARRIVAL_AIRPORT, PILOT_NAME, FLIGHT_STATUS, 
        TICKET_TYPE, PASSENGER_STATUS
    )
    SELECT 
        PASSENGER_ID, 
        FIRST_NAME, 
        LAST_NAME, 
        GENDER, 
        TRY_CAST(AGE AS INT), 
        NATIONALITY, 
        AIRPORT_NAME, 
        AIRPORT_COUNTRY_CODE, 
        COUNTRY_NAME, 
        AIRPORT_CONTINENT, 
        CONTINENTS, 
        TRY_TO_DATE(DEPARTURE_DATE, 'MM/DD/YYYY'),
        ARRIVAL_AIRPORT, 
        PILOT_NAME, 
        FLIGHT_STATUS, 
        TICKET_TYPE, 
        PASSENGER_STATUS
    FROM AIRLINE_DWH.STAGE_1_RAW.RAW_AIRLINE_STREAM
    WHERE METADATA$ACTION = 'INSERT';

    row_count := SQLROWCOUNT;

    INSERT INTO AIRLINE_DWH.STAGE_1_RAW.AUDIT_LOG (PROCEDURE_NAME, ROWS_AFFECTED)
    VALUES ('LOAD_STAGE_2', :row_count);

    COMMIT;

    RETURN 'Successfully loaded ' || :row_count || ' rows into stage 2.';
END;
$$;

CALL AIRLINE_DWH.STAGE_2_INTEGRATION.LOAD_STAGE_2();