CREATE OR REPLACE PROCEDURE AIRLINE_DWH.STAGE_3_CORE.LOAD_STAGE_3()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    INSERT ALL

        INTO AIRLINE_DWH.STAGE_3_CORE.DIM_PASSENGER 
            (PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY)
        VALUES 
            (PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY)

        INTO AIRLINE_DWH.STAGE_3_CORE.DIM_AIRPORT 
            (AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS)
        VALUES 
            (AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS)

        INTO AIRLINE_DWH.STAGE_3_CORE.FACT_FLIGHT_ACTIVITY 
            (PASSENGER_ID, AIRPORT_NAME, DEPARTURE_DATE, FLIGHT_STATUS, TICKET_TYPE)
        VALUES 
            (PASSENGER_ID, AIRPORT_NAME, DEPARTURE_DATE, FLIGHT_STATUS, TICKET_TYPE)

    SELECT 
        PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY,
        AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS,
        DEPARTURE_DATE, FLIGHT_STATUS, TICKET_TYPE
    FROM AIRLINE_DWH.STAGE_2_INTEGRATION.STAGE_2_STREAM;

    COMMIT;

    RETURN 'Star schema successfully loaded.';
END;
$$;