
CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE_3_CORE.FACT_FLIGHT_ACTIVITY (
    PASSENGER_ID VARCHAR,
    DEPARTURE_DATE DATE,
    AIRPORT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR
);

CREATE OR REPLACE STREAM AIRLINE_DWH.STAGE_2_INTEGRATION.CLEAN_AIRLINE_STREAM
ON TABLE AIRLINE_DWH.STAGE_2_INTEGRATION.CLEAN_AIRLINE_DATA;


CREATE OR REPLACE PROCEDURE AIRLINE_DWH.STAGE_3_CORE.LOAD_STAGE_3()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    row_count INTEGER;
BEGIN
    INSERT INTO AIRLINE_DWH.STAGE_3_CORE.FACT_FLIGHT_ACTIVITY (
        PASSENGER_ID, DEPARTURE_DATE, AIRPORT_NAME, FLIGHT_STATUS, TICKET_TYPE
    )
    SELECT 
        PASSENGER_ID, DEPARTURE_DATE, AIRPORT_NAME, FLIGHT_STATUS, TICKET_TYPE
    FROM AIRLINE_DWH.STAGE_2_INTEGRATION.CLEAN_AIRLINE_STREAM
    WHERE METADATA$ACTION = 'INSERT';

    row_count := SQLROWCOUNT;

    INSERT INTO AIRLINE_DWH.STAGE_1_RAW.AUDIT_LOG (PROCEDURE_NAME, ROWS_AFFECTED)
    VALUES ('LOAD_STAGE_3', :row_count);

    COMMIT;

    RETURN 'Successfully loaded ' || :row_count || ' rows into stage 3.';
END;
$$;