USE SCHEMA AIRLINE_DWH.STAGE_3_CORE;

UPDATE FACT_FLIGHT_ACTIVITY 
SET FLIGHT_STATUS = 'Cancelled';

USE SCHEMA AIRLINE_DWH.STAGE_3_CORE;

UPDATE FACT_FLIGHT_ACTIVITY 
SET FLIGHT_STATUS = 'Cancelled';

SELECT FLIGHT_STATUS
FROM FACT_FLIGHT_ACTIVITY
FETCH FIRST 3;

SELECT * FROM FACT_FLIGHT_ACTIVITY AT(OFFSET => -60)
LIMIT 100;

CREATE OR REPLACE TABLE FACT_FLIGHT_RESTORED 
CLONE FACT_FLIGHT_ACTIVITY AT(OFFSET => -60);

SELECT FLIGHT_STATUS
FROM FACT_FLIGHT_RESTORED
FETCH FIRST 3;

DROP TABLE FACT_FLIGHT_RESTORED;

SELECT * FROM FACT_FLIGHT_RESTORED;

UNDROP TABLE FACT_FLIGHT_RESTORED;

SELECT * FROM FACT_FLIGHT_RESTORED;