USE ROLE ACCOUNTADMIN;
USE SCHEMA AIRLINE_DWH.STAGE_3_CORE;

CREATE OR REPLACE SECURE VIEW SECURE_FLIGHT_VIEW AS
SELECT * FROM FACT_FLIGHT_ACTIVITY;

CREATE OR REPLACE ROLE BUSINESS_CLASS_MANAGER;

CREATE OR REPLACE ROW ACCESS POLICY TICKET_SECURITY_POLICY
AS (TICKET_TYPE VARCHAR) RETURNS BOOLEAN ->
    CURRENT_ROLE() = 'ACCOUNTADMIN'
    OR TICKET_TYPE = 'Business';

ALTER VIEW SECURE_FLIGHT_VIEW 
ADD ROW ACCESS POLICY TICKET_SECURITY_POLICY ON (TICKET_TYPE);

GRANT USAGE ON DATABASE AIRLINE_DWH TO ROLE BUSINESS_CLASS_MANAGER;
GRANT USAGE ON SCHEMA AIRLINE_DWH.STAGE_3_CORE TO ROLE BUSINESS_CLASS_MANAGER;
GRANT SELECT ON VIEW SECURE_FLIGHT_VIEW TO ROLE BUSINESS_CLASS_MANAGER;

